### ISSUE TITLE
finding champion id's (key) by user inputting champion's name

### ISSUE THREAD

**Issue by thisKeeWord** [kenany/champion#4]
So i've realized that sending riot a request to receive statistics by champion is rather difficult if the person sending the request does not know the id of the champion to send. 

For example, say in my app I want to send off a request to the ranked summary endpoint of riot's endpoints to obtain information with my Blitzcrank statistics. I would input the champion name Blitzcrank into my form. However, riot's endpoint requires the champion ID and not the name (although I could make a few requests beforehand in order to get the ID of Blitzcrank). Since the majority of potential users only know the name of the champ and not the ID, I felt the need to edit the index.js file you provided that to return the id of the champ for further use.

Here's the edit: 

// modified to not take id but name
var champions = require('./lib/champions');

module.exports = function(value) {
  var i = champions.length;
  while (i--) {
    if (champions[i].name === value) {
      return champions[i]["key"];
    }
  }
  return null;
};

**Comment by kenany** [comment]
Makes sense to me. Might be useful as a new function which this module can export (like `champion.idFromName(name)`, or something shorter).

**Comment by thisKeeWord** [comment]
I'm closing this because it's old af.
